// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct AddressToColorIndexData {
  uint256 mirror;
  uint256 colorIndex;
  uint256 nation;
  string userName;
}

library AddressToColorIndex {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "AddressToColorIn", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462000000000000000000000000000041646472657373546f436f6c6f72496e);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0060030120202000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (address, uint256)
  Schema constant _keySchema = Schema.wrap(0x00340200611f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint256, string)
  Schema constant _valueSchema = Schema.wrap(0x006003011f1f1fc5000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "ownerAddress";
    keyNames[1] = "gameID";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "mirror";
    fieldNames[1] = "colorIndex";
    fieldNames[2] = "nation";
    fieldNames[3] = "userName";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get mirror.
   */
  function getMirror(address ownerAddress, uint256 gameID) internal view returns (uint256 mirror) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get mirror.
   */
  function _getMirror(address ownerAddress, uint256 gameID) internal view returns (uint256 mirror) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set mirror.
   */
  function setMirror(address ownerAddress, uint256 gameID, uint256 mirror) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((mirror)), _fieldLayout);
  }

  /**
   * @notice Set mirror.
   */
  function _setMirror(address ownerAddress, uint256 gameID, uint256 mirror) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((mirror)), _fieldLayout);
  }

  /**
   * @notice Get colorIndex.
   */
  function getColorIndex(address ownerAddress, uint256 gameID) internal view returns (uint256 colorIndex) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get colorIndex.
   */
  function _getColorIndex(address ownerAddress, uint256 gameID) internal view returns (uint256 colorIndex) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set colorIndex.
   */
  function setColorIndex(address ownerAddress, uint256 gameID, uint256 colorIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((colorIndex)), _fieldLayout);
  }

  /**
   * @notice Set colorIndex.
   */
  function _setColorIndex(address ownerAddress, uint256 gameID, uint256 colorIndex) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((colorIndex)), _fieldLayout);
  }

  /**
   * @notice Get nation.
   */
  function getNation(address ownerAddress, uint256 gameID) internal view returns (uint256 nation) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get nation.
   */
  function _getNation(address ownerAddress, uint256 gameID) internal view returns (uint256 nation) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set nation.
   */
  function setNation(address ownerAddress, uint256 gameID, uint256 nation) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((nation)), _fieldLayout);
  }

  /**
   * @notice Set nation.
   */
  function _setNation(address ownerAddress, uint256 gameID, uint256 nation) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((nation)), _fieldLayout);
  }

  /**
   * @notice Get userName.
   */
  function getUserName(address ownerAddress, uint256 gameID) internal view returns (string memory userName) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get userName.
   */
  function _getUserName(address ownerAddress, uint256 gameID) internal view returns (string memory userName) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set userName.
   */
  function setUserName(address ownerAddress, uint256 gameID, string memory userName) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((userName)));
  }

  /**
   * @notice Set userName.
   */
  function _setUserName(address ownerAddress, uint256 gameID, string memory userName) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((userName)));
  }

  /**
   * @notice Get the length of userName.
   */
  function lengthUserName(address ownerAddress, uint256 gameID) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of userName.
   */
  function _lengthUserName(address ownerAddress, uint256 gameID) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of userName.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemUserName(address ownerAddress, uint256 gameID, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of userName.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemUserName(
    address ownerAddress,
    uint256 gameID,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to userName.
   */
  function pushUserName(address ownerAddress, uint256 gameID, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to userName.
   */
  function _pushUserName(address ownerAddress, uint256 gameID, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from userName.
   */
  function popUserName(address ownerAddress, uint256 gameID) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from userName.
   */
  function _popUserName(address ownerAddress, uint256 gameID) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of userName at `_index`.
   */
  function updateUserName(address ownerAddress, uint256 gameID, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of userName at `_index`.
   */
  function _updateUserName(address ownerAddress, uint256 gameID, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(address ownerAddress, uint256 gameID) internal view returns (AddressToColorIndexData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(address ownerAddress, uint256 gameID) internal view returns (AddressToColorIndexData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    address ownerAddress,
    uint256 gameID,
    uint256 mirror,
    uint256 colorIndex,
    uint256 nation,
    string memory userName
  ) internal {
    bytes memory _staticData = encodeStatic(mirror, colorIndex, nation);

    PackedCounter _encodedLengths = encodeLengths(userName);
    bytes memory _dynamicData = encodeDynamic(userName);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    address ownerAddress,
    uint256 gameID,
    uint256 mirror,
    uint256 colorIndex,
    uint256 nation,
    string memory userName
  ) internal {
    bytes memory _staticData = encodeStatic(mirror, colorIndex, nation);

    PackedCounter _encodedLengths = encodeLengths(userName);
    bytes memory _dynamicData = encodeDynamic(userName);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(address ownerAddress, uint256 gameID, AddressToColorIndexData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.mirror, _table.colorIndex, _table.nation);

    PackedCounter _encodedLengths = encodeLengths(_table.userName);
    bytes memory _dynamicData = encodeDynamic(_table.userName);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(address ownerAddress, uint256 gameID, AddressToColorIndexData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.mirror, _table.colorIndex, _table.nation);

    PackedCounter _encodedLengths = encodeLengths(_table.userName);
    bytes memory _dynamicData = encodeDynamic(_table.userName);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint256 mirror, uint256 colorIndex, uint256 nation) {
    mirror = (uint256(Bytes.getBytes32(_blob, 0)));

    colorIndex = (uint256(Bytes.getBytes32(_blob, 32)));

    nation = (uint256(Bytes.getBytes32(_blob, 64)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    PackedCounter _encodedLengths,
    bytes memory _blob
  ) internal pure returns (string memory userName) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    userName = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    PackedCounter _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (AddressToColorIndexData memory _table) {
    (_table.mirror, _table.colorIndex, _table.nation) = decodeStatic(_staticData);

    (_table.userName) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(address ownerAddress, uint256 gameID) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(address ownerAddress, uint256 gameID) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint256 mirror, uint256 colorIndex, uint256 nation) internal pure returns (bytes memory) {
    return abi.encodePacked(mirror, colorIndex, nation);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory userName) internal pure returns (PackedCounter _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = PackedCounterLib.pack(bytes(userName).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory userName) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((userName)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 mirror,
    uint256 colorIndex,
    uint256 nation,
    string memory userName
  ) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(mirror, colorIndex, nation);

    PackedCounter _encodedLengths = encodeLengths(userName);
    bytes memory _dynamicData = encodeDynamic(userName);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(address ownerAddress, uint256 gameID) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(ownerAddress)));
    _keyTuple[1] = bytes32(uint256(gameID));

    return _keyTuple;
  }
}
