// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("ArmyPrices")));
bytes32 constant ArmyPricesTableId = _tableId;

struct ArmyPricesData {
  uint256 priceSwordsman;
  uint256 priceArcher;
  uint256 priceCavalry;
}

library ArmyPrices {
  /** Get the table values' field layout */
  function getFieldLayout() internal pure returns (FieldLayout) {
    uint256[] memory _fieldLayout = new uint256[](3);
    _fieldLayout[0] = 32;
    _fieldLayout[1] = 32;
    _fieldLayout[2] = 32;

    return FieldLayoutLib.encode(_fieldLayout, 0);
  }

  /** Get the table's key schema */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's value schema */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](3);
    _schema[0] = SchemaType.UINT256;
    _schema[1] = SchemaType.UINT256;
    _schema[2] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's key names */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "gameID";
  }

  /** Get the table's field names */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "priceSwordsman";
    fieldNames[1] = "priceArcher";
    fieldNames[2] = "priceCavalry";
  }

  /** Register the table with its config */
  function register() internal {
    StoreSwitch.registerTable(
      _tableId,
      getFieldLayout(),
      getKeySchema(),
      getValueSchema(),
      getKeyNames(),
      getFieldNames()
    );
  }

  /** Register the table with its config (using the specified store) */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, getFieldLayout(), getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /** Get priceSwordsman */
  function getPriceSwordsman(uint256 gameID) internal view returns (uint256 priceSwordsman) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0, getFieldLayout());
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get priceSwordsman (using the specified store) */
  function getPriceSwordsman(IStore _store, uint256 gameID) internal view returns (uint256 priceSwordsman) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0, getFieldLayout());
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set priceSwordsman */
  function setPriceSwordsman(uint256 gameID, uint256 priceSwordsman) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((priceSwordsman)), getFieldLayout());
  }

  /** Set priceSwordsman (using the specified store) */
  function setPriceSwordsman(IStore _store, uint256 gameID, uint256 priceSwordsman) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((priceSwordsman)), getFieldLayout());
  }

  /** Get priceArcher */
  function getPriceArcher(uint256 gameID) internal view returns (uint256 priceArcher) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1, getFieldLayout());
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get priceArcher (using the specified store) */
  function getPriceArcher(IStore _store, uint256 gameID) internal view returns (uint256 priceArcher) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1, getFieldLayout());
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set priceArcher */
  function setPriceArcher(uint256 gameID, uint256 priceArcher) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((priceArcher)), getFieldLayout());
  }

  /** Set priceArcher (using the specified store) */
  function setPriceArcher(IStore _store, uint256 gameID, uint256 priceArcher) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((priceArcher)), getFieldLayout());
  }

  /** Get priceCavalry */
  function getPriceCavalry(uint256 gameID) internal view returns (uint256 priceCavalry) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2, getFieldLayout());
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get priceCavalry (using the specified store) */
  function getPriceCavalry(IStore _store, uint256 gameID) internal view returns (uint256 priceCavalry) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2, getFieldLayout());
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set priceCavalry */
  function setPriceCavalry(uint256 gameID, uint256 priceCavalry) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    StoreSwitch.setField(_tableId, _keyTuple, 2, abi.encodePacked((priceCavalry)), getFieldLayout());
  }

  /** Set priceCavalry (using the specified store) */
  function setPriceCavalry(IStore _store, uint256 gameID, uint256 priceCavalry) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    _store.setField(_tableId, _keyTuple, 2, abi.encodePacked((priceCavalry)), getFieldLayout());
  }

  /** Get the full data */
  function get(uint256 gameID) internal view returns (ArmyPricesData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getFieldLayout());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, uint256 gameID) internal view returns (ArmyPricesData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getFieldLayout());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(uint256 gameID, uint256 priceSwordsman, uint256 priceArcher, uint256 priceCavalry) internal {
    bytes memory _data = encode(priceSwordsman, priceArcher, priceCavalry);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data, getFieldLayout());
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    uint256 gameID,
    uint256 priceSwordsman,
    uint256 priceArcher,
    uint256 priceCavalry
  ) internal {
    bytes memory _data = encode(priceSwordsman, priceArcher, priceCavalry);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    _store.setRecord(_tableId, _keyTuple, _data, getFieldLayout());
  }

  /** Set the full data using the data struct */
  function set(uint256 gameID, ArmyPricesData memory _table) internal {
    set(gameID, _table.priceSwordsman, _table.priceArcher, _table.priceCavalry);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, uint256 gameID, ArmyPricesData memory _table) internal {
    set(_store, gameID, _table.priceSwordsman, _table.priceArcher, _table.priceCavalry);
  }

  /** Decode the tightly packed blob using this table's field layout */
  function decode(bytes memory _blob) internal pure returns (ArmyPricesData memory _table) {
    _table.priceSwordsman = (uint256(Bytes.slice32(_blob, 0)));

    _table.priceArcher = (uint256(Bytes.slice32(_blob, 32)));

    _table.priceCavalry = (uint256(Bytes.slice32(_blob, 64)));
  }

  /** Tightly pack full data using this table's field layout */
  function encode(
    uint256 priceSwordsman,
    uint256 priceArcher,
    uint256 priceCavalry
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(priceSwordsman, priceArcher, priceCavalry);
  }

  /** Encode keys as a bytes32 array using this table's field layout */
  function encodeKeyTuple(uint256 gameID) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    return _keyTuple;
  }

  /* Delete all data for given keys */
  function deleteRecord(uint256 gameID) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    StoreSwitch.deleteRecord(_tableId, _keyTuple, getFieldLayout());
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, uint256 gameID) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(gameID));

    _store.deleteRecord(_tableId, _keyTuple, getFieldLayout());
  }
}
