// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum MineType {
  Food,
  Wood,
  Gold
}

enum State {
  None,
  Waiting,
  Started,
  Completed
}

enum ClashType {
  Castle,
  Mine,
  Dock,
  Battle,
  NavalWar
}

enum AttackerType {
  Army,
  Fleet
}
