// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { ArmyConfig, ArmyConfigData, ArmyConfigTableId } from "./tables/ArmyConfig.sol";
import { ArmyOwnable, ArmyOwnableTableId } from "./tables/ArmyOwnable.sol";
import { CastleOwnable, CastleOwnableTableId } from "./tables/CastleOwnable.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { Players, PlayersTableId } from "./tables/Players.sol";
import { PlayerSeeds, PlayerSeedsTableId } from "./tables/PlayerSeeds.sol";
import { SeedInited, SeedInitedTableId } from "./tables/SeedInited.sol";
import { NumberOfUsers, NumberOfUsersTableId } from "./tables/NumberOfUsers.sol";
import { LimitOfGame, LimitOfGameTableId } from "./tables/LimitOfGame.sol";
import { AddressToUsername, AddressToUsernameData, AddressToUsernameTableId } from "./tables/AddressToUsername.sol";
import { ResourceOwnable, ResourceOwnableData, ResourceOwnableTableId } from "./tables/ResourceOwnable.sol";
import { ResourceInited, ResourceInitedTableId } from "./tables/ResourceInited.sol";
import { GameMetaData, GameMetaDataData, GameMetaDataTableId } from "./tables/GameMetaData.sol";
import { ResourceOwn, ResourceOwnData, ResourceOwnTableId } from "./tables/ResourceOwn.sol";
import { LastCollectTime, LastCollectTimeTableId } from "./tables/LastCollectTime.sol";
import { ResourcesSold, ResourcesSoldData, ResourcesSoldTableId } from "./tables/ResourcesSold.sol";
import { CreditOwn, CreditOwnTableId } from "./tables/CreditOwn.sol";
import { SoldierCreated, SoldierCreatedTableId } from "./tables/SoldierCreated.sol";
import { ResourcePrices, ResourcePricesData, ResourcePricesTableId } from "./tables/ResourcePrices.sol";
import { ArmyPrices, ArmyPricesData, ArmyPricesTableId } from "./tables/ArmyPrices.sol";
import { DockOwnable, DockOwnableTableId } from "./tables/DockOwnable.sol";
import { FleetConfig, FleetConfigData, FleetConfigTableId } from "./tables/FleetConfig.sol";
import { FleetOwnable, FleetOwnableTableId } from "./tables/FleetOwnable.sol";
import { ClashResult, ClashResultData, ClashResultTableId } from "./tables/ClashResult.sol";
import { ColorOwnable, ColorOwnableData, ColorOwnableTableId } from "./tables/ColorOwnable.sol";
import { ChatMessages, ChatMessagesData, ChatMessagesTableId } from "./tables/ChatMessages.sol";
import { LastMessageTime, LastMessageTimeTableId } from "./tables/LastMessageTime.sol";
