// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ArmyConfig, ArmyConfigData } from "./tables/ArmyConfig.sol";
import { ArmyOwnable } from "./tables/ArmyOwnable.sol";
import { ArtilleryOwnable } from "./tables/ArtilleryOwnable.sol";
import { CastleOwnable } from "./tables/CastleOwnable.sol";
import { MapConfig } from "./tables/MapConfig.sol";
import { Position } from "./tables/Position.sol";
import { Players } from "./tables/Players.sol";
import { GarrisonOwnable, GarrisonOwnableData } from "./tables/GarrisonOwnable.sol";
import { CastleHP, CastleHPData } from "./tables/CastleHP.sol";
import { ArtilleryConfig, ArtilleryConfigData } from "./tables/ArtilleryConfig.sol";
import { PlayerSeeds } from "./tables/PlayerSeeds.sol";
import { SeedInited } from "./tables/SeedInited.sol";
import { AddressToUsername } from "./tables/AddressToUsername.sol";
import { AddressToColorIndex, AddressToColorIndexData } from "./tables/AddressToColorIndex.sol";
import { ResourceOwnable, ResourceOwnableData } from "./tables/ResourceOwnable.sol";
import { GameMetaData, GameMetaDataData } from "./tables/GameMetaData.sol";
import { ResourceOwn, ResourceOwnData } from "./tables/ResourceOwn.sol";
import { ResourcesSold, ResourcesSoldData } from "./tables/ResourcesSold.sol";
import { CreditOwn } from "./tables/CreditOwn.sol";
import { SoldierCreated } from "./tables/SoldierCreated.sol";
import { DockOwnable } from "./tables/DockOwnable.sol";
import { FleetConfig, FleetConfigData } from "./tables/FleetConfig.sol";
import { FleetOwnable } from "./tables/FleetOwnable.sol";
import { ClashResult, ClashResultData } from "./tables/ClashResult.sol";
import { ColorOwnable, ColorOwnableData } from "./tables/ColorOwnable.sol";
import { ChatMessages, ChatMessagesData } from "./tables/ChatMessages.sol";
import { FleetCarry, FleetCarryData } from "./tables/FleetCarry.sol";
import { LastMessageTime } from "./tables/LastMessageTime.sol";
import { LatestGameID } from "./tables/LatestGameID.sol";
