// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ArmyConfig, ArmyConfigData, ArmyConfigTableId } from "./tables/ArmyConfig.sol";
import { ArmyOwnable, ArmyOwnableTableId } from "./tables/ArmyOwnable.sol";
import { CastleOwnable, CastleOwnableTableId } from "./tables/CastleOwnable.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { CastleSiegeResult, CastleSiegeResultData, CastleSiegeResultTableId } from "./tables/CastleSiegeResult.sol";
import { BattleResult, BattleResultData, BattleResultTableId } from "./tables/BattleResult.sol";
import { Players, PlayersTableId } from "./tables/Players.sol";
import { PlayerSeeds, PlayerSeedsData, PlayerSeedsTableId } from "./tables/PlayerSeeds.sol";
import { NumberOfUsers, NumberOfUsersTableId } from "./tables/NumberOfUsers.sol";
import { LimitOfGame, LimitOfGameTableId } from "./tables/LimitOfGame.sol";
import { AddressToUsername, AddressToUsernameTableId } from "./tables/AddressToUsername.sol";
import { ResourceOwnable, ResourceOwnableData, ResourceOwnableTableId } from "./tables/ResourceOwnable.sol";
import { ResourceInited, ResourceInitedTableId } from "./tables/ResourceInited.sol";
import { MineCaptureResult, MineCaptureResultData, MineCaptureResultTableId } from "./tables/MineCaptureResult.sol";
import { GameMetaData, GameMetaDataData, GameMetaDataTableId } from "./tables/GameMetaData.sol";
import { ResourceOwn, ResourceOwnData, ResourceOwnTableId } from "./tables/ResourceOwn.sol";
import { LastCollectTime, LastCollectTimeTableId } from "./tables/LastCollectTime.sol";
import { ResourcesSold, ResourcesSoldData, ResourcesSoldTableId } from "./tables/ResourcesSold.sol";
import { CreditOwn, CreditOwnTableId } from "./tables/CreditOwn.sol";
import { SoldierCreated, SoldierCreatedTableId } from "./tables/SoldierCreated.sol";
import { ResourcePrices, ResourcePricesData, ResourcePricesTableId } from "./tables/ResourcePrices.sol";
import { ArmyPrices, ArmyPricesData, ArmyPricesTableId } from "./tables/ArmyPrices.sol";
