// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ArmyConfig, ArmyConfigData, ArmyConfigTableId } from "./tables/ArmyConfig.sol";
import { ArmyOwnable, ArmyOwnableTableId } from "./tables/ArmyOwnable.sol";
import { CastleOwnable, CastleOwnableTableId } from "./tables/CastleOwnable.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { CastleSiegeResult, CastleSiegeResultData, CastleSiegeResultTableId } from "./tables/CastleSiegeResult.sol";
import { BattleResult, BattleResultData, BattleResultTableId } from "./tables/BattleResult.sol";
import { Players, PlayersTableId } from "./tables/Players.sol";
import { PlayerSeeds, PlayerSeedsTableId } from "./tables/PlayerSeeds.sol";
import { NumberOfUsers, NumberOfUsersTableId } from "./tables/NumberOfUsers.sol";
import { LimitOfGame, LimitOfGameTableId } from "./tables/LimitOfGame.sol";
import { AddressToUsername, AddressToUsernameTableId } from "./tables/AddressToUsername.sol";
import { ResourceOwnable, ResourceOwnableData, ResourceOwnableTableId } from "./tables/ResourceOwnable.sol";
import { ResourceInited, ResourceInitedTableId } from "./tables/ResourceInited.sol";
