// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { ArmyConfigData } from "./../index.sol";

/**
 * @title IArmyUpdateSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IArmyUpdateSystem {
  function updateArmy(bytes32 armyID, ArmyConfigData memory newArmyConfig, bytes32 castleID) external;

  function mergeArmy(bytes32 armyOneID, bytes32 armyTwoID, uint256 gameID) external;
}
