// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAttackCaptureSystem {
  function attackToArmy(bytes32 armyOne, bytes32 armyTwo, uint256 gameID) external returns (uint256);
}
