// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IChatSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IChatSystem {
  error ChatSystem__MessageIsTooLong();
  error ChatSystem__NotJoined();
  error ChatSystem__Cooldown();

  function sendMessage(uint256 gameID, string memory message) external;
}
