// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IChatSystem {
  error ChatSystem__MessageIsTooLong();
  error ChatSystem__NotJoined();
  error ChatSystem__Cooldown();

  function sendMessage(uint256 gameID, string memory message) external;
}
