// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IEconomySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEconomySystem {
  function updateEconomyData(uint256 gameID) external;
}
