// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MineType } from "./../common.sol";

/**
 * @title IExchangeSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IExchangeSystem {
  function sellResource(uint256 gameID, uint256 amount, MineType mineType) external;

  function buyResource(uint256 gameID, uint256 amount, MineType mineType) external;
}
