// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MineType } from "./../Types.sol";

interface IExchangeSystem {
  function sellResource(uint256 gameID, uint256 amount, MineType mineType) external;

  function buyResource(uint256 gameID, uint256 amount, MineType mineType) external;
}
