// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameInitSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameInitSystem {
  function initMapData(uint256 gameID, uint32 width, uint32 height, bytes calldata terrain) external;

  function InitNumberOfGamer(uint256 gameID, uint256 capacity) external;

  function InitGame(
    uint256 capacity,
    uint32 width,
    uint32 height,
    bytes calldata terrain,
    string memory name,
    uint8 mapId,
    uint256 firstSeed
  ) external returns (uint256);

  function initUsername(string memory userName) external;

  function joinGame(uint256 gameID, uint256 seed) external;
}
