// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IIdentitySystem {
  function joinGame(uint256 gameID, string memory userName) external;

  function exitGame(uint256 gameID) external;
}
