// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMapSystem {
  error InitSystem__AlreadyInitialized();
  error InitSystem__MismatchedSize();
  error InitSystem__NotEnoughDimension();

  function initMapData(uint256 gameID, uint32 width, uint32 height, bytes calldata terrain) external;
}
