// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { AttackerType } from "./../common.sol";

/**
 * @title IMineCaptureSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMineCaptureSystem {
  function captureMine(bytes32 attackerID, bytes32 mineID, AttackerType attackerType) external;
}
