// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface INavalSystem {
  function buildDock(uint32 coord_x, uint32 coord_y, bytes32 requestedArmy, uint256 gameID) external returns (bytes32);

  function captureDock(bytes32 armyID, bytes32 dockID) external;

  function settleFleet(
    uint32 x,
    uint32 y,
    bytes32 dockID,
    uint32 numSmall,
    uint32 numMedium,
    uint32 numBig,
    uint256 gameID
  ) external returns (bytes32);
}
