// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title INavalSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface INavalSystem {
  function captureDock(bytes32 armyID, bytes32 dockID) external;
}
