// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITestUtilSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITestUtilSystem {
  function economyIncreaseResource(address user, uint256 gameID, uint256 amount) external;

  function economyIncreaseCredit(address user, uint256 gameID, uint256 amount) external;
}
