[profile.default]
solc_version = "0.8.24"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 1
src = "src"
test = "test"
out = "out"
allow_paths = ["../../node_modules", "../../../../packages"]
extra_output_files = ["abi", "evm.bytecode"]
fs_permissions = [{ access = "read", path = "./" }]

[profile.lattice-testnet]
eth_rpc_url = "https://miner.testnet-chain.linfra.xyz/"

[profile.hackathon-testnet]
eth_rpc_url = "https://lattice-goerli-sequencer.optimism.io"

[profile.loot-chain]
eth_rpc_url = "https://testnet.rpc.lootchain.com/http"

[profile.alt-layer]
eth_rpc_url = "https://flashlayer.alt.technology/chaquer281c1962f"

[profile.skale]
eth_rpc_url = "https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix"
